server:
  port: 8080

spring:
  application:
    name: api

wechat:
  server: https://api.weixin.qq.com
  appid: wxfcb47ae4ad192245
  secret: 4a8e527806dad877f102428825049bdb

logging:
  level:
    com.zcy.cn.feign.wechat.server.Auth: debug

info:
  app.name: heathy-server-api
  description: Providing services to wechat