local:
  upload:
    img: /heathy-server-api/src/main/resources/static



#spring:
#  redis:
#    host: localhost
#    port: 6379
#    password:
#    jedis:
#      pool:
#        max-active: 200
#        max-wait: -1
#        max-idle: 10
#        min-idle: 1
#    timeout: 5000
