spring:
  redis:
    host: 47.101.216.18
    port: 6000
    password: ZCYSXJ111.Q
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 1
    timeout: 5000