# 业务趋于稳定之后发布到服务器
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/healthy?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    database: MySQL
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    show-sql: true
    hibernate:
      ddl-auto: create