spring:
  kafka:
    bootstrap-servers: xxxx:xx
    producer:
      retries: 1
      batch-size: 1684
      buffer-memory: 33554432
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer